### ISSUE TITLE
Failed to fetch

### ISSUE THREAD

**Issue by PatrickSantoZZ** [octoman90/BDO-REST-API#6]
o/ 

Ur Guildranking website seems to be fail to fetch the data since a while now. just wanted to let u know. maybe u could look into it.

greetings

**Comment by octoman90** [comment]
Can you provide more information on that? 
- What's the name and region of the guild you're trying to look up?
- What's your browser version?
- Are you behind a firewall or a VPN connection?
- Do you have any non-standard DNS settings?

**Comment by PatrickSantoZZ** [comment]
So far i tried it with some guilds and none of them worked: Tragic / Ebenruth / Flex / Clarity ( EU )
Browser is Opera Version 90 (OPR/90.0.4480.84)
No Firewall or anything
Google DNS but tried with default settings too. didnt changed anything.

greetings~

**Comment by PatrickSantoZZ** [comment]
Yep this one works. i get a response with all guild data fetched.

**Comment by octoman90** [comment]
You are using the leaderboards website at https://bdo.hemlo.cc/leaderboards/, not a self-hosted version, right?
Does the error persist if you refresh the page by pressing Ctrl+Shift+R?

**Comment by PatrickSantoZZ** [comment]
yes im using ur website. on the own hosted version it worked but yea after doing the refresh with CRTL+Shift+R it worked on ur website. thanks

**Comment by octoman90** [comment]
I'm closing the issue then, good that we solved it. And I will look into server configuration, there might be a problem with how caching is configured.
